[tool.poetry]
name = "pyrace"
version = "0.1.0"
description = ""
authors = ["Molly Draven <drazi@duck.com>"]
readme = "README.md"

[tool.poetry.dependencies]
python = "^3.11"
cryptography= "42.0.7"
sentry-sdk = "2.2.0"

[tool.poetry.group.test.dependencies]
pytest = "^8.2.1"


[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
